version: 0.2

phases:
  install:
    commands:
      - echo "Static site - nothing to install"
  build:
    commands:
      - echo "No build needed for static files"
  post_build:
    commands:
      - echo "Build finished on `date`"

artifacts:
  files:
    - '**/*'

