version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static site"
  build:
    commands:
      - echo "No build steps needed for static HTML"
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'

